name: Testing the GitHub Pages publication

on:
  push

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "ruby -v"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.0' # Not needed with a .ruby-version file
    - run: echo "ruby -v"

    # Standard usage
    - uses:  helaili/jekyll-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target_branch: 'gh-pages'
